<?
$PERM["upload"]["7"]="T_8";
$PERM["personal"]["*"]="D";
$PERM["personal"]["G6"]="R";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>