
CREATE TABLE IF NOT EXISTS `hw_channel` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `EPG_ID` INT NOT NULL DEFAULT 0,
    `ICON` VARCHAR(255) NULL,
    `SITE_URL` VARCHAR(255) NULL,
    `IS_NEWS` CHAR(1) NOT NULL DEFAULT 'N',
    `PRICE_H24` DECIMAL NULL,
    `FORBID_REC` CHAR(1) NULL DEFAULT 'N',
    `FRAME_URL` VARCHAR(255) NULL,
    `STREAM_URL` VARCHAR(255) NULL,
    `TITLE` VARCHAR(255) NOT NULL,
    `DESC` TEXT NULL,
    `CODE` VARCHAR(255) NULL,
    `SORT` INT NOT NULL DEFAULT 100,
    `IMG_ID` INT NULL,
    `ACTIVE` char(1) not null default 'Y',
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `hw_image` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `TITLE` VARCHAR(255) NOT NULL,
    `PATH` VARCHAR(255) NOT NULL,
    `WIDTH` INT NULL,
    `HEIGHT` INT NULL,
	PRIMARY KEY (`ID`),
    unique IX_IMAGE_1(PATH)
);

CREATE TABLE IF NOT EXISTS `hw_prog` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `EPG_ID` INT NOT NULL,
    `EPG_SUB_ID` INT NULL,
    `CHANNEL_ID` INT NOT NULL DEFAULT 0,
    `ACTIVE` char(1) NOT null default 'Y',
    `TITLE` VARCHAR(255) NOT NULL,
    `SUB_TITLE` VARCHAR(255) NULL,
    `DESC` TEXT NULL,
    `SEASON` VARCHAR(25) NULL,
    `SERIA` VARCHAR(25) NULL,
    `CATEGORY` VARCHAR(255) NULL,
    `DIRECTOR` VARCHAR(255) NULL,
    `ACTOR` VARCHAR(255) NULL,
    `COUNTRY` VARCHAR(255) NULL,
    `TOPIC` VARCHAR(255) NULL,
    `PRESENTER` VARCHAR(255) NULL,
    `GANRE` VARCHAR(255) NULL,
    `YEAR_LIMIT` VARCHAR(255) NULL,
    `RATING` VARCHAR(255) NULL,
    `HD` CHAR(1) NULL DEFAULT 'N',
    `CODE` VARCHAR(255) NULL,
    `IMG_PREVIEW_ID` INT NULL,
    `IMG_DETAIL_ID` INT NULL,
    `IMG_DOUBLE_ID` INT NULL,
    `IMG_HALF_ID` INT NULL,
    `IMG_VERTICAL_ID` INT NULL,
    `IMG_VERTICAL_DOUBLE_ID` INT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `hw_schedule` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `EPG_ID` INT NOT NULL,
    `CHANNEL_ID` INT NOT NULL DEFAULT 0,
    `PROG_ID` INT NOT NULL DEFAULT 0,
    `START_DATE` DATETIME NULL,
	`END_DATE` DATETIME NULL,
    `DATE` DATE NULL,
    `ACTIVE` char(1) NOT null default 'Y',
    `TITLE` VARCHAR(255) NOT NULL,
    `DESC` TEXT NULL,
    `CODE` VARCHAR(255) NULL,
	PRIMARY KEY (`ID`)
);